### ISSUE TITLE
Failure during Catkin Build

### ISSUE THREAD

**Issue by shlsharma** [UT-ADL/autoware_mini#2]
Hi,
Build failed for these 5 packages:  
Failed         << carla_ros_bridge:cmake                         [ Exited with code 1 ]                               
Failed         <<< carla_ros_bridge                                  [ 0.7 seconds ]                                      
Abandoned <<< autoware_mini                                     [ Unrelated job failed ]                             
Abandoned <<< carla_ackermann_control                    [ Unrelated job failed ]                             
Abandoned <<< carla_ad_demo                                    [ Unrelated job failed ]                             
Abandoned <<< pcl_recorder                                        [ Unrelated job failed ]  

can you please let me know, how to solve this issue?

**Comment by tambetm** [comment]
Can you post the full build log after `catkin clean`? I tried build with the latest versions and it seemed to work fine for me.
